# GET https://iv.ggtyler.dev/api/v1/search?q=%40H2ODEEP2024

# GET https://iv.ggtyler.dev/api/v1/channels/UCoNCFKdiXYWBRk_3Sk06CiA/latest
GET https://iv.ggtyler.dev/api/v1/channels/UCoNCFKdiXYWBRk_3Sk06CiA/videos